// examples/todo-vue/src/App.vue
<script setup lang="ts">
import { dispatch, logSnapshot, setLogLevel } from '@youngdo/rx-state';
import { onMounted, ref, watch } from 'vue';
import { AddTodo, ChangeTodoListStatus, DeleteTodoList } from './store/action';
import { Todo, todoList$ } from './store/states';
import { rxToRef } from './utils';

const calcFilteredTodoList = (todoList: Todo[], filter: Todo['status'] | null) => {
  return todoList.filter(todo => {
    if (filter === null) return true;
    return todo.status === filter;
  });
};

const todoList = rxToRef(todoList$);
const text = ref('');
const filter = ref<Todo['status'] | null>(null);
const filteredTodoList = ref<Todo[]>(calcFilteredTodoList(todoList.value, filter.value));

watch([todoList, filter], ([todoList, filter]) => {
  filteredTodoList.value = calcFilteredTodoList(todoList, filter);
});

const handleKeydown = (e: KeyboardEvent) => {
  e.key === 'Enter' && addTodo();
};
const addTodo = () => {
  if (text.value) {
    dispatch(AddTodo(text.value));
    text.value = '';
  }
};
const changeTodoStatus = (todo: Todo) => {
  const { id, status } = todo;
  const nextStatus = status === 'active' ? 'completed' : 'active';
  dispatch(ChangeTodoListStatus([{ id, status: nextStatus }]));
};
const changeAllCompleted = () => {
  dispatch(
    ChangeTodoListStatus(
      todoList.value.filter(todo => todo.status === 'active').map(todo => ({ id: todo.id, status: 'completed' })),
    ),
  );
};
const deleteTodo = (id: number) => {
  dispatch(DeleteTodoList([id]));
};
const deleteAllCompleted = () => {
  const idList = todoList.value.filter(todo => todo.status === 'completed').map(todo => todo.id);
  dispatch(DeleteTodoList(idList));
};

onMounted(() => {
  setLogLevel('all');
  logSnapshot();

  const changeFilterByHash = () => {
    const hash = location.hash;
    filter.value = hash === '#/active' ? 'active' : hash === '#/completed' ? 'completed' : null;
  };
  window.onhashchange = changeFilterByHash;
  changeFilterByHash();
});
</script>

<template>
  <section class="todoapp">
    <header class="header">
      <h1>todos</h1>
      <input class="new-todo" placeholder="What needs to be done?" v-model="text" @keypress="handleKeydown" />
    </header>
    <section class="main">
      <input id="toggle-all" class="toggle-all" type="checkbox" @click="changeAllCompleted" />
      <label for="toggle-all">Mark all as complete</label>

      <ul class="todo-list">
        <li v-for="todo in filteredTodoList" :key="todo.id" :class="{ completed: todo.completed }">
          <div class="view">
            <input
              :id="'toggle-todo-' + todo.id"
              class="toggle"
              type="checkbox"
              v-model="todo.completed"
              @click="changeTodoStatus(todo)"
            />
            <label :for="'toggle-todo-' + todo.id">{{ todo.text }}</label>
            <button class="destroy" @click="deleteTodo(todo.id)"></button>
          </div>
        </li>
      </ul>
    </section>
    <footer class="footer">
      <span class="todo-count">{{ filteredTodoList.length }}</span>
      <ul class="filters">
        <li>
          <a href="#/" :class="{ selected: filter === null }">All</a>
        </li>
        <li>
          <a href="#/active" :class="{ selected: filter === 'active' }">Active</a>
        </li>
        <li>
          <a href="#/completed" :class="{ selected: filter === 'completed' }">Completed</a>
        </li>
      </ul>
      <button class="clear-completed" @click="deleteAllCompleted">Clear completed</button>
    </footer>
  </section>
</template>

// examples/todo-svelte/src/App.svelte
<script lang="ts">
import { dispatch, logSnapshot, setLogLevel } from '@youngdo/rx-state';
import { onMount } from 'svelte';
import { AddTodo, ChangeTodoListStatus, DeleteTodoList } from './store/action';
import { Todo, todoList$ } from './store/states';

let text: string = '';
let filter: Todo['status'] | null = null;

$: filteredTodoList = $todoList$.filter(todo => {
  if (filter === null) return true;
  return todo.status === filter;
});

const handleKeydown = (e: KeyboardEvent) => {
  e.key === 'Enter' && addTodo();
};
const addTodo = () => {
  if (text) {
    dispatch(AddTodo(text));
    text = '';
  }
};
const changeTodoStatus = (id: number, status: Todo['status']) => () => {
  const nextStatus = status === 'active' ? 'completed' : 'active';
  dispatch(ChangeTodoListStatus([{ id, status: nextStatus }]));
};
const changeAllCompleted = () => {
  dispatch(
    ChangeTodoListStatus(
      todoList$.value.filter(todo => todo.status === 'active').map(todo => ({ id: todo.id, status: 'completed' })),
    ),
  );
};
const deleteTodo = (id: number) => () => {
  dispatch(DeleteTodoList([id]));
};
const deleteAllCompleted = () => {
  const idList = todoList$.value.filter(todo => todo.status === 'completed').map(todo => todo.id);
  dispatch(DeleteTodoList(idList));
};

onMount(() => {
  setLogLevel('all')
  logSnapshot()

  const changeFilterByHash = () => {
    const hash = location.hash;
    filter = hash === '#/active' ? 'active' : hash === '#/completed' ? 'completed' : null;
  };
  window.onhashchange = changeFilterByHash;
  changeFilterByHash();
});
</script>

<section class="todoapp">
  <header class="header">
    <h1>todos</h1>
    <input class="new-todo" placeholder="What needs to be done?" bind:value={text} on:keypress={handleKeydown} />
  </header>
  <section class="main">
    <input id="toggle-all" class="toggle-all" type="checkbox" on:click={changeAllCompleted} />
    <label for="toggle-all">Mark all as complete</label>

    <ul class="todo-list">
      {#each filteredTodoList as todo (todo.id)}
        <li class:completed={todo.status === 'completed'}>
          <div class="view">
            <input
              id={`toggle-todo-${todo.id}`}
              class="toggle"
              type="checkbox"
              checked={todo.status === 'completed'}
              on:click={changeTodoStatus(todo.id, todo.status)}
            />
            <label for={`toggle-todo-${todo.id}`}>{todo.text}</label>
            <button class="destroy" on:click={deleteTodo(todo.id)} />
          </div>
        </li>
      {/each}
    </ul>
  </section>
  <footer class="footer">
    <span class="todo-count">{filteredTodoList.length}</span>
    <ul class="filters">
      <li>
        <a href="#/" class:selected={filter === null}>All</a>
      </li>
      <li>
        <a href="#/active" class:selected={filter === 'active'}>Active</a>
      </li>
      <li>
        <a href="#/completed" class:selected={filter === 'completed'}>Completed</a>
      </li>
    </ul>
    <button class="clear-completed" on:click={deleteAllCompleted}>Clear completed</button>
  </footer>
</section>
